---
apiVersion: v1
kind: Template
metadata:
  name: github-mirror
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: container-security-operator-catalog
    namespace: ${TARGET_NAMESPACE}
  spec:
    displayName: Container Secutiry Operator
    image: ${IMAGE}:${IMAGE_TAG}
    publisher: AppSRE Team
    sourceType: grpc
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: container-security-operator
    namespace: ${TARGET_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: container-security-operator
    namespace: ${TARGET_NAMESPACE}
  spec:
    channel: alpha
    name: container-security-operator
    source: container-security-operator-catalog
    sourceNamespace: ${TARGET_NAMESPACE}
parameters:
- name: IMAGE
  value: quay.io/app-sre/container-security-operator
- name: IMAGE_TAG
  value: latest
- name: TARGET_NAMESPACE
  value: container-security-operator
